services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: daij
      POSTGRES_PASSWORD: daij
      POSTGRES_DB: daij
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
