import { useParams, Link } from 'react-router'
import { useSongs } from '@/useSongs'
import { formatDuration, getProviderImage } from '@/lib/utils'
import { SongRow } from '@/components/SongRow'
import { Button } from '@/components/button'
import { PlayIcon, ShuffleIcon } from '@/components/icons'
import type { Song } from '@/songs'

const providerMeta: Record<
  Song['provider'],
  { label: string; description: string }
> = {
  claude: {
    label: 'Claude',
    description:
      "Tracks composed and arranged by Anthropic's Claude, exploring melodic patterns through code-driven synthesis.",
  },
  chatgpt: {
    label: 'ChatGPT',
    description:
      "Music generated by OpenAI's ChatGPT, blending creative prompting with algorithmic composition.",
  },
  gemini: {
    label: 'Gemini',
    description:
      "Sonic experiments produced by Google's Gemini, translating language into layered soundscapes.",
  },
}

function formatTotalDuration(seconds: number) {
  const hrs = Math.floor(seconds / 3600)
  const mins = Math.floor((seconds % 3600) / 60)
  if (hrs > 0) return `${hrs} hr ${mins} min`
  return `${mins} min`
}

export const Provider = () => {
  const { provider } = useParams<{ provider: string }>()
  const { songs, play } = useSongs()

  const meta = providerMeta[provider as Song['provider']]

  if (!meta) {
    return (
      <div className="min-h-screen px-5 pt-12">
        <div className="mx-auto w-full max-w-7xl">
          <p className="text-secondary px-5 py-12 text-center text-sm">
            Provider not found.
          </p>
        </div>
      </div>
    )
  }

  const providerSongs = songs?.filter((s) => s.provider === provider) ?? []
  const totalDuration = providerSongs.reduce((sum, s) => sum + s.duration, 0)
  const coverImage = getProviderImage(provider)

  return (
    <div className="min-h-screen px-5 pt-12">
      <div className="mx-auto w-full max-w-7xl">
        {/* Hero */}
        <div className="flex gap-5 pb-6">
          <img
            src={coverImage}
            alt={meta.label}
            className="size-36 shrink-0 rounded-xl object-cover sm:size-44"
          />
          <div className="flex flex-col justify-end">
            <p
              className="text-secondary uppercase"
              style={{ font: '600 11px/1.27 var(--font-sans)' }}
            >
              Collection
            </p>
            <h1
              className="text-primary mt-1"
              style={{ font: '700 34px/1.176 var(--font-sans)' }}
            >
              {meta.label}
            </h1>
            <p
              className="text-secondary mt-2 max-w-md"
              style={{ font: '400 13px/1.38 var(--font-sans)' }}
            >
              {meta.description}
            </p>
            <p
              className="text-tertiary mt-2"
              style={{ font: '400 12px/1.25 var(--font-sans)' }}
            >
              {providerSongs.length}{' '}
              {providerSongs.length === 1 ? 'song' : 'songs'} &middot;{' '}
              {formatTotalDuration(totalDuration)}
            </p>
          </div>
        </div>

        {/* Actions */}
        {providerSongs.length > 0 && (
          <div className="flex items-center gap-3 pb-6">
            <Button onClick={() => play(providerSongs[0], providerSongs)}>
              <PlayIcon className="size-3.5" />
              Play all
            </Button>
            <Button
              onClick={() => {
                const shuffled = [...providerSongs].sort(
                  () => Math.random() - 0.5,
                )
                play(shuffled[0], shuffled)
              }}
            >
              <ShuffleIcon className="size-3.5" />
              Shuffle
            </Button>
          </div>
        )}

        {/* Song list */}
        <div className="border-divider border-t">
          <div
            className="border-divider text-secondary flex items-center border-b px-5 py-2"
            style={{ font: '400 11px/1.27 var(--font-sans)' }}
          >
            <span className="w-8 shrink-0 text-center">#</span>
            <span className="ml-3 flex-1">Title</span>
            <span className="w-14 shrink-0 text-right">Listens</span>
            <span className="w-14 shrink-0 text-right">Wins</span>
            <span className="w-14 shrink-0 text-right">ELO</span>
            <span className="w-14 shrink-0 text-right">Time</span>
          </div>

          {!songs ? (
            <p
              className="text-secondary py-12 text-center"
              style={{ font: '400 13px/1.23 var(--font-sans)' }}
            >
              Loading...
            </p>
          ) : providerSongs.length === 0 ? (
            <p
              className="text-secondary py-12 text-center"
              style={{ font: '400 13px/1.23 var(--font-sans)' }}
            >
              No tracks yet.
            </p>
          ) : (
            providerSongs.map((song, i) => (
              <SongRow
                key={song.name}
                song={song}
                index={i + 1}
                showProvider={false}
                queue={providerSongs}
                trailing={
                  <div
                    className="flex items-center"
                    style={{ font: '400 12px/1.25 var(--font-sans)' }}
                  >
                    <span className="text-secondary w-14 shrink-0 text-right">
                      {song.listens}
                    </span>
                    <span className="text-secondary w-14 shrink-0 text-right">
                      {song.wins}
                    </span>
                    <span
                      className="text-primary w-14 shrink-0 text-right"
                      style={{ fontWeight: 600 }}
                    >
                      {Math.round(song.eloRating)}
                    </span>
                    <span className="text-secondary w-14 shrink-0 text-right">
                      {formatDuration(song.duration)}
                    </span>
                  </div>
                }
              />
            ))
          )}
        </div>
      </div>
    </div>
  )
}
