import { useParams, Link } from 'react-router'
import { useSongs } from '@/useSongs'
import { getProviderImage } from '@/lib/utils'
import { SongRow } from '@/components/SongRow'
import type { Song } from '@/songs'

const providerMeta: Record<
  Song['provider'],
  { label: string; description: string }
> = {
  claude: {
    label: 'Claude',
    description:
      "Tracks composed and arranged by Anthropic's Claude, exploring melodic patterns through code-driven synthesis.",
  },
  chatgpt: {
    label: 'ChatGPT',
    description:
      "Music generated by OpenAI's ChatGPT, blending creative prompting with algorithmic composition.",
  },
  gemini: {
    label: 'Gemini',
    description:
      "Sonic experiments produced by Google's Gemini, translating language into layered soundscapes.",
  },
}

function formatDuration(seconds: number) {
  const mins = Math.floor(seconds / 60)
  const secs = seconds % 60
  return `${mins}:${secs.toString().padStart(2, '0')}`
}

function formatTotalDuration(seconds: number) {
  const hrs = Math.floor(seconds / 3600)
  const mins = Math.floor((seconds % 3600) / 60)
  if (hrs > 0) return `${hrs} hr ${mins} min`
  return `${mins} min`
}

export const Provider = () => {
  const { provider } = useParams<{ provider: string }>()
  const { songs, play } = useSongs()

  const meta = providerMeta[provider as Song['provider']]

  if (!meta) {
    return (
      <div className="min-h-screen">
        <div className="mx-auto w-full max-w-6xl border-x">
          <header className="border-b p-6">
            <Link
              to="/"
              className="text-fg-muted text-sm transition-colors hover:text-black"
            >
              &larr; Home
            </Link>
          </header>
          <p className="text-fg-muted p-6 text-sm">Provider not found.</p>
        </div>
      </div>
    )
  }

  const providerSongs = songs?.filter((s) => s.provider === provider) ?? []
  const totalDuration = providerSongs.reduce((sum, s) => sum + s.duration, 0)
  const coverImage = getProviderImage(provider)

  return (
    <div className="min-h-screen">
      <div className="mx-auto w-full max-w-6xl border-x">
        <header className="border-b p-6">
          <div className="flex items-center gap-4">
            <Link
              to="/"
              className="text-fg-muted text-sm transition-colors hover:text-black"
            >
              &larr; Home
            </Link>
            <span className="text-fg-muted">/</span>
            <h1 className="font-serif text-2xl font-extrabold tracking-tight text-black">
              {meta.label}
            </h1>
          </div>
        </header>

        {/* Hero */}
        <div className="flex gap-6 border-b p-6">
          <img
            src={coverImage}
            alt={meta.label}
            className="size-36 shrink-0 object-cover sm:size-44"
          />
          <div className="flex flex-col justify-end">
            <p className="text-fg-muted text-xs font-medium tracking-widest uppercase">
              Collection
            </p>
            <h2 className="mt-1 font-serif text-3xl font-extrabold text-black sm:text-4xl">
              {meta.label}
            </h2>
            <p className="text-fg-muted mt-2 max-w-md text-sm leading-relaxed">
              {meta.description}
            </p>
            <p className="text-fg-muted mt-2 text-sm">
              {providerSongs.length}{' '}
              {providerSongs.length === 1 ? 'song' : 'songs'} &middot;{' '}
              {formatTotalDuration(totalDuration)}
            </p>
          </div>
        </div>

        {/* Actions */}
        {providerSongs.length > 0 && (
          <div className="flex items-center gap-3 border-b p-6">
            <button
              onClick={() => play(providerSongs[0], providerSongs)}
              className="border border-black bg-black px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-transparent hover:text-black"
            >
              Play all
            </button>
            <button
              onClick={() => {
                const shuffled = [...providerSongs].sort(
                  () => Math.random() - 0.5,
                )
                play(shuffled[0], shuffled)
              }}
              className="border px-5 py-2 text-sm font-medium text-black transition-colors hover:bg-black hover:text-white"
            >
              Shuffle
            </button>
          </div>
        )}

        {/* Song list */}
        <div>
          {/* Table header */}
          <div className="text-fg-muted flex items-center border-b px-6 py-2.5 text-xs font-medium">
            <span className="w-8 shrink-0 text-center">#</span>
            <span className="ml-4 flex-1">Title</span>
            <span className="w-16 shrink-0 text-right">Wins</span>
            <span className="w-16 shrink-0 text-right">ELO</span>
            <span className="w-16 shrink-0 text-right">Duration</span>
          </div>

          {!songs ? (
            <p className="text-fg-muted py-12 text-center text-sm">
              Loading...
            </p>
          ) : providerSongs.length === 0 ? (
            <p className="text-fg-muted py-12 text-center text-sm">
              No tracks yet.
            </p>
          ) : (
            providerSongs.map((song, i) => (
              <SongRow
                key={song.name}
                song={song}
                index={i + 1}
                showProvider={false}
                queue={providerSongs}
                trailing={
                  <div className="flex items-center text-sm">
                    <span className="w-16 shrink-0 text-right text-fg-muted">
                      {song.wins}
                    </span>
                    <span className="w-16 shrink-0 text-right font-semibold text-black">
                      {Math.round(song.eloRating)}
                    </span>
                    <span className="w-16 shrink-0 text-right text-fg-muted">
                      {formatDuration(song.duration)}
                    </span>
                  </div>
                }
              />
            ))
          )}
        </div>
      </div>
    </div>
  )
}
